### ISSUE TITLE
User Story: Initial DevOps Deployment Metrics

### ISSUE THREAD

**Issue by tomwillis608** [flexion/devops-deployment-metrics#22]
# Initial DevOps Deployment Metrics

## User Story 1

As an engineering team,
So that I can understand our software delivery performance,
I want to automate the calculation of deployment metrics for our production applications.

## Acceptance criteria:

- [x] Deployment frequency metrics are written to a CSV file
- [x] Change fail percentage metrics are written to a CSV file
- [x] Deployment mean time to recover metrics are written to a CSV file
- [x] GitHub credentials are not in the repository

## Preconditions:

- [x] The operator has access to the GitHub repository.
- [x] The applications the team deploys use GitHub workflows for deployment.
- [x] The team may have one or more applications.

## Non-requirements for this story:

- [x] Publish this tool to PyPI
- [x] Polished documents

## Tasks:

- [x] Set up repository
- [x] Pre-commit hooks
- [x] Continuous integration
	- [x] Pre-commit tests
	- [x] Unit tests
	- [x] SCA (Safety). Bandit also scans as a SAST.
- [x] Write metrics  
- [x] Validate results on two repositories. 
  - [x] CDC TI @basiliskus @halprin 
  - [x] EQRS FC @tomwillis608 
- [x] Initial threat model @tomwillis608 #138 
- [x] Initial load/performance test @tomwillis608 - try action-benchmark @tomwillis608  #479  
- [x] Base deployment frequency on successful deployments only, ala DORA @basiliskus #154 
- [x] Restore loading progress indicator (tqdm) @basiliskus #155 
- [x] Add ADR for using Renovate for dependency management @tomwillis608  #478

## Decisions:
- [x] TOML for configuration
- [x] Python for application code
- [x] Hypermodern Python Project cookie cutter 
- [x] `black` and `reorder-python-imports` for code style

## Definition of Done:

- [x] Acceptance criteria met - The system meets all acceptance criteria
- [x] Feature toggles created - Features that are deployed but not released have toggles 
- [x] Usability validated - Team ensures the working code is easy to use [@basiliskus check Done if you agree]
- [x] Code refactored for clarity - Developers can understand the work simply by reviewing the code [@basiliskus check Done if you agree]
- [x] Dependency Rule followed - More important code doesn’t directly depend on less important code [@basiliskus check Done if you agree]
- [x] Development debt eliminated - UX and code aligns to the team’s latest understanding of the domain
- [x] Source code merged - Code has been merged into the main branch
- [x] 25% unit test coverage achieved - Automated test coverage tools indicate coverage of >= 25%. Increment to 90% over time
- [x] Code reviewed - Code is reviewed by at least one other team members before being merged
- [x] Code quality checks passed - Code passes all automated quality checks
- [x] Security scans passed - Code passes expected scans for vulnerabilities and compliance issues
- [x] Threat model updated - The threat model incorporates new threats and remediations 
- [x] Build process updated - Automated build process include code supporting the user story
- [x] Load/performance tests passed - Performance tests include the functionality of the user story
- [x] Documents are updated - All required documentation is up to date and version controlled, including ADRs
