### ISSUE TITLE
User Story: Run On Windows

### ISSUE THREAD

**Issue by tomwillis608** [flexion/devops-deployment-metrics#285]
**User Story 2**

As an Windows user,
So that I can operate on my laptop,
I need the application to run on Windows 10 and Windows 11.

Implements feature request #206 

**Acceptance criteria:**

- [x]  Application runs to success on Windows 11 in PowerShell terminal @basiliskus 
- [x]  Application runs to success on Windows 11 in "DOS" command line terminal @basiliskus 
- [x] Application runs to success on Windows 10 in PowerShell terminal @tomwillis608 
- [x] Applications runs to success on Windows 10 in "DOS" command line terminal @tomwillis608 
- [x]  README lists supported OSes

**Preconditions:**

-  Configuration exists that works in a Linux or Mac environment.

**Tasks:**

- [x] Run CI/CD Tests workflow on `windows-latest` #286 
- [x] Resolve `TypeError: can't compare offset-naive and offset-aware datetimes` error in `metrics.py` line 62 not seen when run on Linux #291
- [x] Update README @tomwillis608 #303

**Decisions:**

**Definition of Done:**

- [x]  Acceptance criteria met - The system meets all acceptance criteria
- [x]  Feature toggles created - Features that are deployed but not released have toggles
- [x]  Usability validated - Team ensures the working code is easy to use
- [x]  Code refactored for clarity - Developers can understand the work simply by reviewing the code 
- [x]  Dependency Rule followed - More important code doesn’t directly depend on less important code 
- [x]  Development debt eliminated - UX and code aligns to the team’s latest understanding of the domain
- [x]  Source code merged - Code has been merged into the main branch
- [x]  90% unit test coverage achieved - Automated test coverage tools indicate coverage of >= 90%. Increment to 100% over time
- [x]  Code reviewed - Code is reviewed by at least one other team members before being merged
- [x]  Code quality checks passed - Code passes all automated quality checks
- [x]  Security scans passed - Code passes expected scans for vulnerabilities and compliance issues
- [x]  Threat model updated - The threat model incorporates new threats and remediations
- [x]  Build process updated - Automated build process include code supporting the user story #286
- [x]  Load/performance tests passed - Performance tests include the functionality of the user story
- [x]  Documents are updated - All required documentation is up to date and version controlled, including ADRs

**Comment by basiliskus** [comment]
I can help test this on Windows 11 if you need. I have a laptop running Win11

**Comment by tomwillis608** [comment]
@basiliskus if you want to grab either of the tasks identified so far, put your name by the task and go for  it!

**Comment by basiliskus** [comment]
I ran the application in Windows 11 (Home edition), with the same configuration parameters we're using for CDC-TI, and everything completed as expected. I also ran all `nox` sessions and they completed successfully. 

I tested in cmd "DOS" and powershell 7.3.8, using python 3.9. Everything running as expected.
