### ISSUE TITLE
Protect all action runners with step-security

### ISSUE THREAD

**Issue by tomwillis608** [flexion/devops-deployment-metrics#502]
## Tasks

- [x] Add step-security on audit mode to all workflows #503
   - [x] auto-merge-depdendabot-workflow
   - [x] codeql
   - [x] labeler
   - [x] release
   - [x] tests
- [ ] After a soak, go to `block` mode #707 
   - [ ] auto-merge-depdendabot-workflow
   - [ ] benchmark
   - [ ] codeql
   - [ ] labeler
   - [ ] release
   - [ ] tests
- [ ] Update contributing.md  
- [x] Add ADR #503
